services:
  eth-node:
    image: ethereum/client-go:v1.14.11
    ports:
      - 8545:8545
      - 8546:8546
    command: --verbosity 1
      --http.vhosts '*,localhost,host.docker.internal'
      --http
      --http.api eth,net,web3,debug
      --http.corsdomain '*'
      --http.addr "0.0.0.0"
      --ws
      --ws.api eth,net,web3,debug
      --ws.origins '*'
      --ws.addr "0.0.0.0"
      --networkid 1337
      --dev
      --dev.period 0
      --allow-insecure-unlock
      --rpc.allow-unprotected-txs
      --dev.gaslimit 20000000
  fund-signer:
    build: funder
    environment:
      - FUND=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
      - ETH_RPC_URL=http://eth-node:8545
      - ENTRYPOINT=0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789
    restart: on-failure:3
    depends_on:
      eth-node:
        condition: service_started