[build]
pre-build = [
    "apt-get update && apt-get -y upgrade && apt-get install -y wget pkg-config llvm-dev libclang-6.0-dev clang-6.0 libssl-dev ca-certificates",
    "wget -c https://github.com/ethereum/solidity/releases/download/v0.8.27/solc-static-linux && mv solc-static-linux /usr/local/bin/solc && chmod a+x /usr/local/bin/solc"
]

[build.env]
passthrough = [
    "JEMALLOC_SYS_WITH_LG_PAGE",
]
