imports_granularity = "Crate"
use_small_heuristics = "Max"
comment_width = 100
wrap_comments = true
binop_separator = "Back"
format_code_in_doc_comments = true
doc_comment_code_block_width = 100
group_imports = "One"
