on:
  push:
    branches:
      - main

name: docker

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: build and push docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      # github action worker got about 14GB available space for building which is not enough
      # remove some unused binary in the image to get more spaces
      - name: Make more space to compilation
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@1.81.0
      
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - uses: taiki-e/install-action@cross

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch third-party dependencies
        run: |
          make fetch-thirdparty

      - name: Setup Yarn cache - submodule "thirdparty/account-abstraction"
        uses: actions/setup-node@v3
        with:
          node-version: '16.17'
          cache: 'yarn'
          cache-dependency-path: crates/contracts/thirdparty/account-abstraction
    
      - name: Setup Yarn cache - submodule "thirdparty/bundler"
        uses: actions/setup-node@v3
        with:
          node-version: '16.17'
          cache: 'yarn'
          cache-dependency-path: tests/thirdparty/bundler

      - name: Install solc
        run: .github/scripts/install_solc.sh

      - name: Set up Docker builder
        run: |
          docker run --privileged --rm tonistiigi/binfmt --install arm64,amd64
          docker buildx create --use --name cross-builder

      - name: Build and push Silius image
        run: make docker-build-push
